version: "3"

services:
  bitsongdnode0:
    container_name: bitsongdnode0
    image: "bitsongofficial/go-bitsong"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-bitsongd.log}
    volumes:
      - ./build:/desmosd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  bitsongdnode1:
    container_name: bitsongdnode1
    image: "bitsongofficial/go-bitsong"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-bitsongd.log}
    volumes:
      - ./build:/bitsongd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  bitsongdnode2:
    container_name: bitsongdnode2
    image: "bitsongofficial/go-bitsong"
    environment:
      - ID=2
      - LOG=${LOG:-bitsongd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/bitsongd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  bitsongdnode3:
    container_name: bitsongdnode3
    image: "bitsongofficial/go-bitsong"
    environment:
      - ID=3
      - LOG=${LOG:-bitsongd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/bitsongd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
